### ISSUE TITLE
Meteor Toys does not see the collections

### ISSUE THREAD

**Issue by adrianmc** [thereactivestack/kickstart-meteor-react-flowrouter#22]
This is easy to reproduce. Simply clone a fresh project, install the Meteor Toys package, and notice that the Todos collection isn't being detected by Meteor Toys on the bottom left. Has anyone had any success making this work?

@msavin

**Comment by eXon** [comment]
I'll take a look at it and see how we can make them both work together

**Comment by adrianmc** [comment]
Thanks @eXon , I've also e-mailed Max Savin (creator of Meteor Toys) and he said he'll be looking into this as well. btw, good work on this project! It's been very helpful so far.

**Comment by Yellowhill** [comment]
Any news on this front?

**Comment by eXon** [comment]
Not sure this is still relevant with Meteor 1.3 and NPM. I don't think anything special is required in Webpack for this.
