### ISSUE TITLE
React from npm

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-meteor-react-flowrouter#25]
Hi

I am a bit confused about react and where is it used from. You essentially use a react package from meteor and not a NPM version. Yet, react IS installed in the node_modules directory as it is required by the dependencies installe in webpack.packages.json. Does not this collide? Can I just use react from NPM? Thanks!

**Comment by eXon** [comment]
Now with meteor-webpack 1.0 you can use React from NPM. If it detects the react-runtime package, it will use it. Otherwise the NPM package will be used.

**Comment by tomitrescak** [comment]
Great, thanks!
