### ISSUE TITLE
npm WARN prefer global npm@3.5.3 should be installed with -g

### ISSUE THREAD

**Issue by rkstar** [thereactivestack/kickstart-meteor-react-flowrouter#27]
i was getting this error when running `meteor` on my app:
```
npm WARN prefer global npm@3.5.3 should be installed with -g
```

then it would compile just fine but with a TON of these types of warnings:
```
npm WARN In npm@3.5.3 replacing bundled version of node-gyp with node-gyp@3.2.1
```

i tried with `npm v 3.5.3` and `npm 3.6.0` installed globally on my systerm and got the same results.

**Comment by eXon** [comment]
NPM is not anymore installed with meteor-webpack :)
