### ISSUE TITLE
Unable to import React

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-meteor-react-flowrouter#29]
Hi

When I do `import React from "react`
and then try to reference `React.Component` ... the generated babel code fails

The only way to do this is with:

`import { Component } from "react"`

The weird thing is that in my older project it works, but when I reset tyhe project and re-create npm modules it now fails.

Any idea?

**Comment by eXon** [comment]
Still a problem with the new version?

**Comment by tomitrescak** [comment]
All good! ;) Great work. I could remove react-runtime as well as react-meteor-data. Lovin it!
