### ISSUE TITLE
Configuring webpack (e.g. plugins)

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-meteor-react-flowrouter#30]
@eXon fantastic! woo hoo! Time for a beer now ;))

I have one question though, I do not understand how do I configure my webpack instance. I work with JSX control statements plugin and it has to be configured with babel. How can I achieve that? Thanks! Do I only insert .babelrc file ?

**Comment by eXon** [comment]
You could easily write a Meteor package that add plugins to babel.

The .babelrc file is not read ATM but I think it would be easy and really useful to automatically add it to the config. Can you share your config?

**Comment by tomitrescak** [comment]
@exon this is my current config. Not much, mostly original stuff. Important is the custom plugins for Babel and custom uglify plugin.

```
var webpack = require('webpack');

var babelSettings = { presets: [ 'react', 'es2015', 'stage-0' ] };
babelSettings.plugins = ['transform-decorators-legacy', 'jsx-control-statements'];

if (process.env.NODE_ENV !== 'production' && !process.env.IS_MIRROR) {
  babelSettings.plugins.push(['react-transform', {
    transforms: [{
      transform: 'react-transform-hmr',
      imports: ['react'],
      locals: ['module']
    }, {
      transform: 'react-transform-catch-errors',
      imports: ['react', 'redbox-react']
    }]
    // redbox-react is breaking the line numbers :-(
    // you might want to disable it
  }]);
}

module.exports = {
  entry: './entry',
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'babel?' + JSON.stringify(babelSettings) + '!ts', exclude: /node_modules|lib/ },
      { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
      { test: /\.(svg|ttf|woff2?|eot)(\?.*)?$/, loader: 'file' }
    ]
  }
};

if (process.env.NODE_ENV == 'production') {
  module.exports.plugins = [
    new webpack.optimize.UglifyJsPlugin({minimize: true})
  ]
}
```

If you give me  hint on how can I go on, maybe I can help out.
I guess the uglify plugin can go into the new "webpack.json" file.

But where would I include those plugins for babel?
Thanks!

**Comment by eXon** [comment]
@tomitrescak 

You can update your webpack:react plugin and it will read the .babelrc file :)

For the UglifyJsPlugin, it is already automatically added in production. I'm looking for your minimize flag and it doesn't seem to do anything. Am I wrong?

The only missing feature is webpack:typescript. Care to help me understand how the configuration works and what loader / plugins most people are using?

I'll need some help there but it is one of my priority to support TypeScript. I know it is widely used.

**Comment by tomitrescak** [comment]
I tested it and the `.babelrc` way works flawlesly. On the doc page you mention that it is possible to achieve also with "babel.plugins" config in webpack.json, that did not work for me. Maybe I did something wrong. But am veeery happy with .babelrc.

**Comment by tomitrescak** [comment]
Concerning typescript. The best loader to use is "ts-loader". you can see the configuration above consisting of configuring the ts(x) loading and a hot loader parameters (babel settings) for them:

```
module.exports = {
  entry: './entry',
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'babel?' + JSON.stringify(babelSettings) + '!ts', exclude: /node_modules|lib/ },
      ....
    ]
  }
};
```

While this is great, I always end up NOT using the loader, and keep TS files in the src folder, and compiling them into "apps" folder. It just makes the whole app MUCH faster. But for webpack:typescript, definitelly you need the configuration from above. Very simple.
