### ISSUE TITLE
Doesn't Work in Production

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-meteor-react-flowrouter#32]
when running `meteor --production` following errors appear in the web console:

```
Uncaught Error: can't wait after FlowRouter has been initialized
Cannot read property 'ServiceConfiguration' of undefined(anonymous function) @ 
Uncaught Error: FlowRouter is already initialized
```

**Comment by eXon** [comment]
Someone made a PR about that recently. Have you tried adding Meteor.startup to FlowRouter.initialize()?

**Comment by tomitrescak** [comment]
Hmm .. does not seem to help ;(

**Comment by eXon** [comment]
Are is your FlowRouter version? Are you using ssr? Have you cloned this repo and just run `meteor --production`? (for me this works)

**Comment by tomitrescak** [comment]
No. This is happening in my Mantra version which is a copy of the flowrouter project. I will check tomorrow file by file what is different and let you know.

**Comment by tomitrescak** [comment]
All good, copying a fresh new version and following your advice worked.

**Comment by tomitrescak** [comment]
Thanks for your help!
