### ISSUE TITLE
Unable to get SSR work

### ISSUE THREAD

**Issue by sammkj** [thereactivestack/kickstart-meteor-react-flowrouter#34]
When I first tried webpack with FR SSR, I got it working. But now, I'm not able to get it working with a clean project. Here's my current folder structure:

```
/src
  /app
  /server
  client.js
  meteor.startup.js
  server.js
```

**Comment by eXon** [comment]
You'll need to be more specific with your error and how you setup ssr

**Comment by sammkj** [comment]
@eXon , thanks for replying!

I'm using [kickstart-mantra-webpack](https://github.com/mantrajs/kickstart-mantrajs-webpack) but with `flow-router-ssr`. I didn't see any errors, it's just I couldn't get SSR to work. When I viewed page source, there was nothing in the body tag. I also created a [sample repo](https://github.com/sammkj/mantra-webpack-ssr).

**Comment by sammkj** [comment]
Previously I got it to work. But now, I don't know why it's not working anymore.

**Comment by sammkj** [comment]
I tried moving folders around like this:

```
/,meteor
/app
/lib
/server
meteor.startup.js
```

But still I'm seeing empty body tag. Any guidance would be greatly appreciated!

**Comment by eXon** [comment]
That's weird. I'll take a look when I have some time for this.

**Comment by sammkj** [comment]
Ok, thanks!

**Comment by sammkj** [comment]
I was able to get SSR to work by importing `/app/entry` in `/server/entry`.
