### ISSUE TITLE
Webpack folder Question

### ISSUE THREAD

**Issue by txs** [thereactivestack/kickstart-meteor-react-flowrouter#35]
I'm using this package to kickstart.
https://github.com/D1no/touch2s
and I change the router to flowrouter-ssr by atmosphere.

I'm new to webpack.

I don't know where to place your  ( FlowRouter.wait() ) cause I don't have a src folder.
please help thanks!

**Comment by eXon** [comment]
You can put it in a `meteor.startup.js` file in `entry/client`.

**Comment by txs** [comment]
Also where should  I put the client.js for the meteor.startup
FlowRouter.initial()?

2016-03-16 3:23 GMT+08:00 Benoit Tremblay <notifications@github.com>:

**Comment by txs** [comment]
Thanks


2016-05-08 0:21 GMT+08:00 Benoit Tremblay <notifications@github.com>:
