### ISSUE TITLE
[Windows 7 64bit] Cannot resolve grandparent directory

### ISSUE THREAD

**Issue by reohjs** [thereactivestack/kickstart-meteor-react-flowrouter#39]
Hi, wondering if anyone can shed some light on these errors:

![terminal errors](http://puu.sh/oUc6e/53f1dcd5ed.png)

Why would it be trying to resolve a directory 2 levels up!?

**Comment by eXon** [comment]
This is really weird. Can you share your project or steps to reproduce?

**Comment by reohjs** [comment]
@eXon I just ran the installation steps (git clone etc.) it's a fresh project, no changes

**Comment by reohjs** [comment]
Looks like it doesn't like `!` in path names: just to rule out pathing issues, I cloned to a different directory on a different drive and it ran fine. Added `!` to the folder name and the error came back.

(2nd error was just that I forgot to `npm install` on that particular clone)
