### ISSUE TITLE
Inadequate instructions?  or what?  localhost:3500 CONNECTION_REFUSED

### ISSUE THREAD

**Issue by martinhbramwell** [thereactivestack/kickstart-meteor-react-flowrouter#40]
I really thought these kickstarters were going to help me, but I can't get started **at all** !!

If I follow your README.md naively : 

```bash
git clone git@github.com:thereactivestack/kickstart-meteor-react-flowrouter.git
Cloning into 'kickstart-meteor-react-flowrouter'...
remote: Counting objects: 249, done.
remote: Total 249 (delta 0), reused 0 (delta 0), pack-reused 249
Receiving objects: 100% (249/249), 786.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (99/99), done.
Checking connectivity... done.
you@trykick:~/projex$ cd kickstart-meteor-react-flowrouter/
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ 
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ 
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ meteor
meteor: command not found
```

Huh?  Wasn't mentioned as a pre-requisite.  Ok let's try ...

```bash
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ 
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ 
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ curl https://install.meteor.com/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                         Dload  Upload   Total   Spent    Left  Speed
100  6675    0  6675    0     0  10782      0 --:--:-- --:--:-- --:--:-- 10783
Downloading Meteor distribution
######################################################################## 100.0%

Meteor 1.3.2.4 has been installed in your home directory (~/.meteor).
```

. . .  and run it again . . . 

```bash
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ meteor
[[[[[ ~/projex/kickstart-meteor-react-flowrouter ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
webpack built 8b0c69991fd6d6c06975 in 79ms   |                                     
Hash: 8b0c69991fd6d6c06975
Version: webpack 1.13.0
Time: 79ms
 Asset     Size  Chunks       Chunk Names
web.js  22.5 kB       0       main
chunk    {0} web.js (main) 40 bytes [rendered]
    [0] multi main 40 bytes {0} [built] [2 errors]

ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /home/you/projex/kickstart-meteor-react-flowrouter
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'babel' in /home/you/projex/kickstart-meteor-react-flowrouter
 @ multi main
=> Errors prevented startup:                  
	   
   While processing files with webpack:webpack (for target os.linux.x86_64):
   src/server.js: Entry module not found: Error: Cannot resolve module 'babel' in /home/you/projex/kickstart-meteor-react-flowrouter
   resolve module babel in /home/you/projex/kickstart-meteor-react-flowrouter
	   
=> Your application has errors. Waiting for file change.
^C                                            
you@trykick:~/projex/kickstart-meteor-react-flowrouter$
you@trykick:~/projex/kickstart-meteor-react-flowrouter$
```

Hmmm. Right.  So ```meteor``` is a prerequisite -- unmentioned.

Maybe ```npm``` is an unmentioned prerequisite too?
Let's try the standard ```apt``` version. **Might** be ok ....

```bash
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ sudo apt install npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
    :       :       :
    :       :       :
Setting up node-sha (1.2.3-1) ...
Setting up node-slide (1.1.4-1) ...
Setting up npm (3.5.2-0ubuntu4) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
```

Trying that again ...

```bash
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ npm install
kickstart-meteor-react-router@1.0.0 /home/you/projex/kickstart-meteor-react-flowrouter
├── babel@6.5.2 
├─┬ babel-core@6.9.0 
│ ├─┬ babel-code-frame@6.8.0 
    :       :       :
    :       :       :
│ │   │   │ │   ├── isobject@2.1.0 
│ │   │   │ │   └── randomatic@1.1.5 
│ │   │   │ ├── preserve@0.2.0 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
    :       :       :
    :       :       :
└─┬ webpack-hot-middleware@2.10.0 
  ├── ansi-html@0.0.5 
  ├── html-entities@1.2.0 
  ├── querystring@0.2.0 
  └─┬ strip-ansi@3.0.1 
	└── ansi-regex@2.0.0 
```

Oh great!  Is that ```/chokidar/fsevents:  ``` glitch 'coz I need a different version of ```npm```???  Let's hope not ...

```bash
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ meteor
[[[[[ ~/projex/kickstart-meteor-react-flowrouter ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
webpack built 6279b95e3b4c131ad11e in 6651ms /
=> Started your app.                          
	                                          
=> App running at: http://localhost:3000/     
^C                                            
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ 
```

Seems to work on localhost . . . and . . .  *Yup* I can create a user and a ToDo item.  Good.  Maybe we have something going here.

Let's try on another machine ...

*¡¡ Rats !!*  Blank Page . . .  but *view page source* shows a ton of loaded packages.

Console shows error : 

    GET http://localhost:3500/assets/web.js net: ERR_CONNECTION_REFUSED

Why in **hell** is it looking at localhost port 3500 **on the other machine** ????
So, is that due to a wrong ```npm``` version?  Wrong Meteor version? 

```bash
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ npm --version
3.5.2
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ node --version
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ meteor --version
Meteor 1.3.2.4
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
you@trykick:~/projex/kickstart-meteor-react-flowrouter$ 
```

**Comment by martinhbramwell** [comment]
I just discovered that I **can** connect from another machine if I run with : 

```bash
meteor run --production
```

Is this expected?  It would have been nice to have been told in the README. :-(

**Comment by scheung38** [comment]
Why just a blank page whether meteor or meteor run --production?

Console error says : 

    TodoApp.jsx?26d5:46 Uncaught ReferenceError: React is not defined

**Comment by martinhbramwell** [comment]
@scheung38 Did you solve this?

**Comment by scheung38** [comment]
Spent the last 2 days and still have not had proper build from 

meteor add webpack

C:\Users\seb\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_
modules\fibers\future.js:245
W20160601-17:23:43.457(1)? (STDERR)                                             throw(ex);
W20160601-17:23:43.457(1)? (STDERR)                                                   ^
W20160601-17:23:43.457(1)? (STDERR) ReferenceError: module is not defined

**Comment by martinhbramwell** [comment]
I have no idea how to help you on Windows.  My advice - - give up on it, and run Ubuntu in  a virtual machine (Hyper-V or VirtualBox or VMWare) or in a docker container like this one : [Meteor / CircleCI Tutorial -- #0 Create a Docker Machine](https://www.youtube.com/watch?v=UzA3ddE0XPA)

**Comment by scheung38** [comment]
Is this correct syntax?

"main": "src/server.js",
"browser": "src/client.js",

as it complaints that server cannot be found, for Win 7 these need to be 

"main": "src\server.js",
"browser": "src\client.js",

?

**Comment by luckyyang** [comment]
@scheung38 `Uncaught ReferenceError: React is not defined`

I have the same problem, have you solved it?

**Comment by luckyyang** [comment]
> Uncaught ReferenceError: React is not defined

```
npm uninstall react react-dom
npm install react react-dom --save
```
then restart the server solve my problem

**Comment by MaxArrowhead** [comment]
I'm having the same problems on Windows 10.

"meteor" works fine (without error message), but at http://localhost:3000 i get a blue blank page and in the browser console the error

"Uncaught ReferenceError: React is not defined             TodoApp.jsx?26d5:46"


Any Ideas?

**Comment by MaxArrowhead** [comment]
On my Ubuntu 14.04 Machine i'm getting the following error:


maximilian@maximilian-ThinkPad-Edge-E545:~/Desktop/kickstart20170721$ meteor
[[[[[ ~/Desktop/kickstart20170721 ]]]]]       

=> Started proxy.                             
=> Started MongoDB.                           
webpack built 8b0c69991fd6d6c06975 in 132ms  -                                  
Hash: 8b0c69991fd6d6c06975
Version: webpack 1.13.0
Time: 132ms
 Asset     Size  Chunks       Chunk Names
web.js  22.5 kB       0       main
chunk    {0} web.js (main) 40 bytes [rendered]
    [0] multi main 40 bytes {0} [built] [2 errors]

ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /home/maximilian/Desktop/kickstart20170721
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'babel' in /home/maximilian/Desktop/kickstart20170721
 @ multi main
=> Errors prevented startup:                  
   
   While processing files with webpack:webpack (for target os.linux.x86_64):
   src/server.js: Entry module not found: Error: Cannot resolve module 'babel'
   in /home/maximilian/Desktop/kickstart20170721
   resolve module babel in /home/maximilian/Desktop/kickstart20170721
   
=> Your application has errors. Waiting for file change.



how can this be?

**Comment by martinhbramwell** [comment]
It's not possible to help you without a lot more details of what you did and what you observed.

**Comment by olumytee** [comment]
@MaxArrowhead You need to add React to the import statement at the top like so:
`import **React,** { Component, PropTypes } from 'react';`

**Comment by eXon** [comment]
Added help in readme
